# permissions for end users to edit etcdclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdcluster-editor-role
rules:
- apiGroups:
  - etcd.my.domain
  resources:
  - etcdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etcd.my.domain
  resources:
  - etcdclusters/status
  verbs:
  - get
